title: Riffol
description: Initialization system in Rust.

tagline: Initialization system in Rust
pitch: >-
  Riffol is a supervising process that can run as a traditional daemon on Unix-like systems,
  or as an init system for containers.

social:
  links:
    - https://twitter.com/riboseinc
    - https://github.com/riboseinc/riffol

legal:
  name: Riffol
  tos_link: https://www.ribose.com/tos
  privacy_policy_link: https://www.ribose.com/privacy

parent_hub:
  git_repo_url: https://github.com/riboseinc/open.ribose.com
  home_url: https://open.ribose.com/

home_calls_to_action:
  - { url: "/software/riffol/docs/readme/", title: "Get Started" }
  - { url: "https://github.com/riboseinc/riffol/releases/", title: "Download" }

# These are required for the theme to work:

theme: jekyll-theme-open-project
permalink: /blog/:month-:day-:year/:title/
